#!/bin/sh

ptestdir=$(dirname "$(readlink -f "$0")")
cd "$ptestdir"/tests || exit

tests=$(find * -type f -name 'test_suite_*')
failed=0

for f in $tests
do
    if test -x ./"$f"; then
        if ./"$f" > ./"$f".out 2> ./"$f".err; then
            echo "PASS: $f"
        else
            echo "FAIL: $f"
            ((failed++))
        fi
    fi
done

exit $failed
