require conf/distro/poky.conf
require adi-distro-shared.conf

DISTRO = "adi-distro-glibc"
DISTRO_NAME = "Analog Devices Inc Reference Distro (glibc)"

TARGET_VENDOR = "-adi_glibc"
SDK_VENDOR = "-adi_glibc_sdk"

DISTRO_FEATURES:remove = "sysvinit"
DISTRO_FEATURES:append = " systemd"
DISTRO_FEATURES_OPTED_OUT = "sysvinit"
VIRTUAL-RUNTIME_dev_manager = "udev"
VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_login_manager = "systemd"

DISTRO_FEATURES_FILTER_NATIVE:append = " systemd"
DISTRO_FEATURES_NATIVE:remove = "sysvinit"
DISTRO_FEATURES_NATIVE:append = " systemd"

DISTRO_FEATURES_FILTER_NATIVESDK:append = " systemd"
DISTRO_FEATURES_NATIVESDK:remove = "sysvinit"
DISTRO_FEATURES_NATIVESDK:append = " systemd"

INIT_MANAGER = "systemd"
