FROM ubuntu:22.04

ENV version=v1
ENV DEBIAN_FRONTEND=noninteractive
ARG bashrc=https://raw.githubusercontent.com/analogdevicesinc/doctools/refs/heads/ci/bashrc
ARG entrypoint_sh=https://raw.githubusercontent.com/analogdevicesinc/doctools/refs/heads/ci/entrypoint.sh
ARG git_defaults_sh=https://raw.githubusercontent.com/analogdevicesinc/doctools/refs/heads/ci/git-defaults.sh
ARG gh_actions_runner_sh=https://raw.githubusercontent.com/analogdevicesinc/doctools/refs/heads/ci/gh-actions-runner.sh

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates curl jq coreutils

RUN useradd -m runner
WORKDIR /home/runner

ADD ${gh_actions_runner_sh} .
RUN bash ./gh-actions-runner.sh ; rm ./gh-actions-runner.sh

# Install packages required by Yocto Scarthgap for Ubuntu:
# https://docs.yoctoproject.org/ref-manual/system-requirements.html#ubuntu-and-debian
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential chrpath cpio debianutils diffstat file gawk gcc git \
    iputils-ping libacl1 liblz4-tool locales python3 python3-git \
    python3-jinja2 python3-pexpect python3-pip python3-subunit socat \
    texinfo unzip wget xz-utils zstd \
    && rm -rf /var/lib/apt/lists/*

# Configure locale for Yocto
RUN locale-gen en_US.UTF-8 && update-locale LANG=en_US.UTF-8
ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US:en \
    LC_ALL=en_US.UTF-8

RUN mkdir -p /usr/local/bin
WORKDIR /usr/local/bin
ADD ${entrypoint_sh} .
RUN chmod +rx ./entrypoint.sh

ADD ${git_defaults_sh} .
RUN bash ./git-defaults.sh ; rm ./git-defaults.sh

USER runner
WORKDIR /home/runner
RUN curl -o .bashrc -L ${bashrc} ; \
    chmod +x .bashrc

ENTRYPOINT ["/bin/bash"]
