[Service]
Environment=TERM=vt220
TTYReset=no
TTYVHangup=no
ExecStart=
ExecStart=-/usr/sbin/agetty --noreset --noclear --issue-file=/etc/issue:/etc/issue.d:/run/issue.d:/usr/lib/issue.d --keep-baud 115200 - $TERM
