#!/usr/bin/sh

# Configure Jupyter
mkdir -pv /root/.jupyter/
cat << EOF > /root/.jupyter/jupyter_lab_config.py
# Configuration file for lab.
import platform
c = get_config()  # noqa
c.ServerApp.allow_origin = '*'
c.ServerApp.allow_remote_access = True
c.ServerApp.allow_root = True
c.ServerApp.ip = platform.node() + ".local"
EOF

swapdev=$(losetup -f)

# Create a loop device for the swapfile
losetup $swapdev /swapfile

# Setup swap
mkswap $swapdev
swapon $swapdev
