name: Build ADI Yocto artifacts

on:
  workflow_dispatch:
    inputs:
      machine:
        description: "Yocto machine"
        default: "adsp-sc598-som-ezkit"
      image:
        description: "Yocto image"
        default: "adsp-sc5xx-minimal"
      manifest:
        description: "Manifest"
        default: main
      manifest-repo:
        description: "Manifest repository"
        default: ""
      override-meta-adi:
        description: "Override sources/meta-adi with the checked-out ref"
        type: boolean
        default: false
  workflow_call:
    inputs:
      machine:
        type: string
        default: "adsp-sc598-som-ezkit"
      image:
        type: string
        default: "adsp-sc5xx-minimal"
      manifest:
        type: string
        default: main
      manifest-repo:
        type: string
        default: ""
      override-meta-adi:
        type: boolean
        default: false
    secrets:
      APP_CLIENT_ID:
        required: false
      APP_PRIVATE_KEY:
        required: false


permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ vars.RUNNER != '' && fromJSON(vars.RUNNER) || 'ubuntu-latest' }}
    steps:
      - uses: actions/create-github-app-token@v3
        if: ${{ github.repository_owner == 'adi-innersource' }}
        id: app-token
        with:
          app-id: ${{ secrets.APP_CLIENT_ID  }}
          private-key: ${{ secrets.APP_PRIVATE_KEY  }}
          owner: ${{ github.repository_owner }}
          repositories: |
            linux
            u-boot
            lnxdsp-adi-meta
            lnxdsp-adi-security-meta
            lnxdsp-repo-manifest
            lnxdsp-scripts
            openocd

      - name: Checkout
        uses: actions/checkout@v7
        with:
          token: ${{ steps.app-token.outputs.token || github.token }}

      - name: Build
        uses: ./actions/build
        with:
          machine: ${{ inputs.machine }}
          image: ${{ inputs.image }}
          manifest: ${{ inputs.manifest }}
          manifest-repo: ${{ inputs.manifest-repo }}
          override-meta-adi: ${{ inputs.override-meta-adi }}
          gh-token: ${{ steps.app-token.outputs.token || github.token }}

      - name: Upload release archive to release
        uses: svenstaro/upload-release-action@v2
        if: ${{ github.event_name == 'release' }}
        with:
          repo_token: ${{ github.token }}
          file: ${{ env.YOCTO_WORKSPACE }}/images-${{ inputs.machine }}-${{ inputs.image }}-${{ github.event.release.tag_name }}.tar.xz
          tag: ${{ github.ref }}

      - name: Upload SDK installer to release
        uses: svenstaro/upload-release-action@v2
        if: ${{ github.event_name == 'release' }}
        with:
          repo_token: ${{ github.token }}
          file: ${{ env.SDK_INSTALLER }}
          tag: ${{ github.ref }}
