name: Build ADI Yocto artifacts

on:
  workflow_dispatch:
    inputs:
      machine:
        description: "Yocto machine"
        default: "adsp-sc598-som-ezkit"
      image:
        description: "Yocto image"
        default: "adsp-sc5xx-minimal"
      manifest:
        description: "Manifest"
        default: main
      manifest-repo:
        description: "Manifest repository"
        default: ""
      override-meta-adi:
        description: "Override sources/meta-adi with the checked-out ref"
        type: boolean
        default: false
  workflow_call:
    inputs:
      machine:
        type: string
        default: "adsp-sc598-som-ezkit"
      image:
        type: string
        default: "adsp-sc5xx-minimal"
      manifest:
        type: string
        default: main
      manifest-repo:
        type: string
        default: ""
      override-meta-adi:
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ vars.RUNNER != '' && fromJSON(vars.RUNNER) || 'ubuntu-latest' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Build
        uses: ./actions/build
        with:
          machine: ${{ inputs.machine }}
          image: ${{ inputs.image }}
          manifest: ${{ inputs.manifest }}
          manifest-repo: ${{ inputs.manifest-repo }}
          override-meta-adi: ${{ inputs.override-meta-adi }}

      - name: Upload release archive to release
        uses: svenstaro/upload-release-action@v2
        if: ${{ github.event_name == 'release' }}
        with:
          repo_token: ${{ github.token }}
          file: ${{ env.YOCTO_WORKSPACE }}/images-${{ inputs.machine }}-${{ inputs.image }}-${{ github.event.release.tag_name }}.tar.xz
          tag: ${{ github.ref }}

      - name: Upload SDK installer to release
        uses: svenstaro/upload-release-action@v2
        if: ${{ github.event_name == 'release' }}
        with:
          repo_token: ${{ github.token }}
          file: ${{ env.SDK_INSTALLER }}
          tag: ${{ github.ref }}
