name: Publish release

on:
  release:
    types: [published]

permissions:
  contents: write
  actions: read

jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Attach release assets
        uses: ./actions/publish-release
