name: Build ADI Yocto artifacts (main)

on:
  workflow_dispatch:
    inputs:
      manifest-branch:
        description: "Manifest repository branch/ref"
        default: "main"
  pull_request:
  push:
    branches:
      - "main"
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        machine:
          - adsp-sc573-ezlite
          - adsp-sc589-mini
          - adsp-sc594-som-ezkit
          - adsp-sc594-som-ezlite
          - adsp-sc598-som-ezkit
          - adsp-sc598-som-ezlite
          - adsp-sc846-som-ezkit
        image:
          - adsp-sc5xx-minimal
          - adsp-sc5xx-full
        manifest:
          - main
        include:
          - machine: adsp-sc573-ezlite
            image: adsp-sc5xx-tiny
            manifest: main
            build-sdk: false
            upload-artifacts: true
          - image: adsp-sc5xx-minimal
            build-sdk: true
            upload-artifacts: true
          - image: adsp-sc5xx-full
            build-sdk: true
            upload-artifacts: false

    uses: ./.github/workflows/build.yml
    secrets:
      APP_CLIENT_ID: ${{ secrets.TOKEN_GENERATOR_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.TOKEN_GENERATOR_APP_PRIVATE_KEY }}
    permissions:
      contents: write
    with:
      machine: ${{ matrix.machine }}
      image: ${{ matrix.image }}
      manifest: ${{ matrix.manifest }}
      manifest-branch: ${{ inputs.manifest-branch }}
      build-sdk: ${{ matrix.build-sdk }}
      upload-artifacts: ${{ matrix.upload-artifacts }}
      override-meta-adi: true

  deploy_cloudsmith:
    needs: [build]
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository || github.event_name == 'push' }}
    uses: analogdevicesinc/linux/.github/workflows/upload-to-cloudsmith.yml@ci
    secrets:
      CLOUDSMITH_SERVICE_SLUG: ${{ secrets.CLOUDSMITH_SERVICE_SLUG }}
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    permissions:
      id-token: write
      contents: read
      actions: read
    with:
      artifacts: >
        *
