name: Build ADI Yocto artifacts (main)

on:
  workflow_dispatch:
  pull_request:
  release:
    types: [published]
  schedule:
    - cron: '0 5 * * 1' # 05:00 UTC every Monday

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        machine:
          - adsp-sc598-som-ezkit
        image:
          - adsp-sc5xx-minimal
        manifest:
          - main

    uses: ./.github/workflows/build.yml
    secrets: inherit
    permissions:
      contents: read
    with:
      machine: ${{ matrix.machine }}
      image: ${{ matrix.image }}
      manifest: ${{ matrix.manifest }}
      override_meta_adi: true
